### ISSUE TITLE
Vectorize IPv4 deserialization

### ISSUE THREAD

**Issue by k0ekk0ek** [NLnetLabs/simdzone#23]
Deserialization of IPv4 addresses seems like a good candidate for vectorization. Implementations may vary in efficiency, but the [version in glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=resolv/inet_pton.c;h=fae52145cc59d3418db63c7ab107fa7309ff1a5a;hb=HEAD) requires quite a bit of scalar logic. I'm not quite sure I like the size of the lookup table in the StackOverflow post [Fastest way to get IPv4 address from string](https://stackoverflow.com/q/31679341), but a 7.8x speedup is presumably possible.

**Comment by k0ekk0ek** [comment]
The [SIMD-ized faster parse of IPv4 addresses](http://0x80.pl/notesen/2023-04-09-faster-parse-ipv4.html) article by Wojciech Muła describes how to parse IP addresses 2-3 times more efficient.

**Comment by lemire** [comment]
I will have a look.

**Comment by lemire** [comment]
@k0ekk0ek Does the zone standard require that the IPv4 addresses be in the common decimal.dot.decimal.dot.... format where each decimal is a byte value in decimal form?

**Comment by lemire** [comment]
On it.

**Comment by k0ekk0ek** [comment]
@lemire, what may be good to know is that the values may be quoted in the future.

The obvious use case is the `A` record.
```
foo.example.com. IN A 192.0.2.1
```
But with the addition of SVCB the address may also be in the `ipv4hint` parameter ([draft](https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-12.html#name-ipv4hint-and-ipv6hint)).
```
foo.example.com. IN SVCB 0 bar.example.com. ipv4hint="192.0.2.1,192.0.2.2"
```

The key=parameter is one token if contiguous, two if it's quoted. i.e. key="parameter" (check if `key=` is followed `"` and call `lex` again if it is, otherwise add the length of the key to `char` pointer). I propose we worry about the A record first and worry about SVCB later (not an RFC yet and very likely not common in TLD zones).

Also, I plan to drop the `length` member from the token (as outlined in #30). I think you don't need it (wouldn't be useful for the SVCB either) scanning the article(?). You can safely assume a complete token and a padding of 64 bytes. You may also safely assume the token is not quoted (`code` member is not in the token yet, but will be, in which case it'll say either `CONTIGUOUS` or `QUOTED`).

To check if the field is correctly delimited, I plan to add a table named `contiguous` (or similar). Something like [this](https://github.com/k0ekk0ek/scanner/blob/63af61c822ba6238dab1aad5752621ddf07b2ffb/src/lexer.h#L30). For non-string fields the character after the token can be looked up, which will give us the new state. In this case I'd probably check `contiguous[ (uint8_t)*p ] != CONTIGUOUS` or something. For more sophisticated use cases, I plan to add a table called `delimiters`, which points to the correct delimiter table for the `code` member (`const uint8_t *delimiters = { NULL, contiguous, quoted };`). So there you'd be able to do a check like `delimiters[ token->code ][ (uint8_t)*p ] != token->code` (valid only for `CONTIGUOUS` and `QUOTED` fields).

Sorry for the wall of text. Of course these plans are all open for discussion. I don't think they impact your work on this, but I thought it would be good to share them just in case. Of course, any of the plans are "dumb", be sure to let me know :sweat_smile:.

**Comment by lemire** [comment]
I don't think any of this is a problem.

**Comment by lemire** [comment]
Still working on it. It is quite interesting. (I will have something for you soon.)

**Comment by k0ekk0ek** [comment]
Sounds good!

Meanwhile... Parser code is being altered to work without length. I did a quick implementation for IPv4 addresses (not tested etc). Don't mind if this gets dropped, but maybe it's useful to you as a fallback? (Looking at the code it's faster than `memcpy` + `inet_pton`).

```
zone_nonnull_all
static zone_really_inline void parse_ip4(
  zone_parser_t *parser,
  const zone_type_info_t *type,
  const zone_field_info_t *field,
  token_t *token)
{
  int32_t r;

  if ((r = have_contiguous(parser, type, field, token)) < 0)
    return r;

  uint8_t *o = &parser->rdata->octets[parser->rdata->length];
  const uint8_t *os = o;

  *o = 0;
  for (const char *ps = p;; p++) {
    const uint64_t d = (uint8_t)*p - '0';
    if (d <= 9) {
      *o = *o * 10 + (uint8_t)d;
    } else {
      if (!(p - ps) || p - ps > 3 || *o > 255 || o - os > 3)
        SYNTAX_ERROR(parser, "Invalid %s in %s", NAME(field), NAME(type));
      ps = p + 1;
      os++;
      if (*p != '.')
        break;
      *os = 0;
    }
  }

  if (contiguous[ (uint8_t)*p ] == CONTIGUOUS || o - os != 3)
    SYNTAX_ERROR(parser, "Invalid %s in %s", NAME(field), NAME(type));

  parser->rdata->length += 4;
  return ZONE_IP4;
}
```

**Comment by lemire** [comment]
I couldn't work on the IP4 problem today (had a busy day at the office) but I am resuming the work tomorrow.

Basically, I think that Wojciech is brilliant (as usually), but we can do better, possibly much better. But I need time coding.

I will report back. And yeah, we need a fallback, always.

**Comment by k0ekk0ek** [comment]
@lemire, the work done on #64 (still needs polish, focused on getting numbers fast), shows what the structures will be like should you need that information.

**Comment by lemire** [comment]
I will post something today.

**Comment by lemire** [comment]
Parsing IP addresses crazily fast 
https://lemire.me/blog/2023/06/08/parsing-ip-addresses-crazily-fast/

Code (in C) at https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2023/06/08/src/sse_inet_aton.c

**Comment by k0ekk0ek** [comment]
Awesome work and a very nice blog post @lemire. Thank you for mentioning NLnet Labs, it's appreciated! I suspect you want to issue a PR yourself(?), but if you'd rather have me integrate it, that's fine too.

**Comment by lemire** [comment]
I will issue a PR.

**Comment by lemire** [comment]
PR at https://github.com/NLnetLabs/simdzone/pull/65
