### ISSUE TITLE
Vectorize base32 decoding

### ISSUE THREAD

**Issue by k0ekk0ek** [NLnetLabs/simdzone#28]
Base32 encoding is used in `NSEC3` records ([RFC5155](https://www.rfc-editor.org/rfc/rfc5155)) to hash the next owner name and may appear quite a lot in DNSSEC signed zones  (not the case for `.se`, but is the case for e.g. `.com`). Like base16 and base64, this encoding may be eligible for vectorization too.

**Comment by k0ekk0ek** [comment]
No, Base32 is only used in [NSEC3](https://www.rfc-editor.org/rfc/rfc5155#section-3) ([presentation format](https://www.rfc-editor.org/rfc/rfc5155#section-3.3)). The data there is not the last field and hence must be presented as one contiguous set of characters.

Example from [Appendix A in RFC5155](https://www.rfc-editor.org/rfc/rfc5155#appendix-A):
```
  NSEC3   1 1 12 aabbccdd (
                            2vptu5timamqttgl4luu9kg21e0aor3s A RRSIG )
```

**Comment by aqrit** [comment]
> pretend the above works flawlessly


The input can be hashed/sliced into  into groups of 8 instead 16.
However, that requires a fixup for signed chars.

```
const __m128i delta_check = _mm_setr_epi8(-128, -128, -128, -128, -128, -128, -50, -128, -65, 0, 0, 0x7F - 0x5A, -97, 0, 0, 0x7F - 0x7A);
const __m128i delta_rebase = _mm_setr_epi8(0, 0, 0, 0, 0, 0, -24, 0, -65, -65, -65, -65, -97, -97, -97, -97);

__m128i v = _mm_loadu_si128(__m128i*)src);
__m128i hash_key = _mm_and_si128(_mm_srli_epi32(v, 3), _mm_set1_epi8(0x0F));

// unpacked binary-coded-duotrigesimal
__m128i data = _mm_add_epi8(_mm_shuffle_epi8(delta_rebase, hash_key), v);

// bad char check
__m128i check = _mm_shuffle_epi8(delta_check, hash_key);
check = _mm_or_si128(_mm_add_epi8(check, v), v); // fixup signed chars
if(_mm_movemask_epi8(check)) {
	; // bad char detected
}

// todo: pack bits

```

**Comment by lemire** [comment]
I will have a look this week.

**Comment by aqrit** [comment]
Should we know how many base32hex digits to expect before starting decoding?

Anyways, decoding seems fairly uninteresting.
Here is an bare kernel:
https://gist.github.com/aqrit/ee41f2fe222b3cb68aaf7facd5cd08a6

**Comment by k0ekk0ek** [comment]
Thank you @aqrit! Looks pretty straightforward indeed. I'll play with it after the weekend and go from there. Much appreciated! @lemire, are you interested in reviewing and benchmarking too? The current code is terrible, so that might make for a fun write-up as well? :slightly_smiling_face:

**Comment by lemire** [comment]
Yes. It is on my todo as well.

**Comment by k0ekk0ek** [comment]
Only looked at the simd variant (yet), but nice work @aqrit! Should make for a nice speedup (.com zone file contains it). Only thing we have to add is checking for correct padding, which is easy to add (especially because we don't have to account for whitespace). Thanks!

I especially like your range check, pretty clever.

(of course, I'll look at the swar version for the fallback parser too)

**Comment by lemire** [comment]
Ok. Let me build this up a big and see what we can make out of it... :-)

**Comment by lemire** [comment]
I hope to have something later today.

**Comment by lemire** [comment]
Ok. So in my tests, SWAR is effectively useless. The scalar approach is faster. I have even have a slightly faster one (base32hex_fast) that can reach 2.5 GB/s (about 10% faster than the routine/scalar approach). The SIMD approach is about 2.5 times faster in my tests. You can gain a bit of speed by using 256-bit vectors (AVX) but not that much. All the functions can slightly overwrite to the output buffer and overread in the input buffer.

For my benchmark, I use short inputs ("F1S6QOJADHQMKS3GCLIN4RB9F1Q6UT37") and there is no inlining, which means that each call has to pay for register initialization and all that, which explains the lack of power of the wide SIMD approach.

```
base32hex_avx                  :   7.55 GB/s  235.9 Ma/s   4.24 ns/d   3.23 GHz  13.70 c/d  61.21 i/d    0.4 c/b   1.91 i/b   4.47 i/c 
base32hex_simd                 :   7.02 GB/s  219.3 Ma/s   4.56 ns/d   3.23 GHz  14.72 c/d  70.21 i/d    0.5 c/b   2.19 i/b   4.77 i/c 
base32hex_fast                 :   2.53 GB/s   79.0 Ma/s  12.65 ns/d   3.21 GHz  40.57 c/d  194.21 i/d    1.3 c/b   6.07 i/b   4.79 i/c 
base32hex_simple               :   2.35 GB/s   73.4 Ma/s  13.62 ns/d   3.21 GHz  43.69 c/d  231.21 i/d    1.4 c/b   7.23 i/b   5.29 i/c 
base32hex_swar                 :   1.98 GB/s   61.7 Ma/s  16.20 ns/d   3.20 GHz  51.85 c/d  230.21 i/d    1.6 c/b   7.19 i/b   4.44 i/c 
```

As before, I have made my code available...
https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/2023/07/19

They are all maxing out the "instructions per cycle". So it is an instance where lowering the number of instructions is critical. Sadly, this might be a tad difficult for short inputs.

If you know that the size of the input (@aqrit raised this point), you can gain a bit of speed. I suspect it is not that much...

**Comment by k0ekk0ek** [comment]
Good stuff @lemire. Good to have this documented, don't know if this is used in many other places, but people can at least find it on the internet now.

Can you include [this](https://github.com/NLnetLabs/nsd/blob/a7f2ff544f16fd9f6b74fd847a7e097985bdb648/util.c#L731) version too? It doesn't make sense from a performance perspective, but it nicely shows where we started from(?)

We also have to check for padding(?) We can use the zero_mask trick but with equals signs instead. Modulo with 8, pick the right mask and compare?

**Comment by lemire** [comment]
> We also have to check for padding(?)

I followed @aqrit's idea and we don't really validate the padding. Basically, you can stop the stream and put any garbage (not just `=`) and it will work. (It should work.)

But sure, we can try to check that we have `=`, as you describe.

**Comment by aqrit** [comment]
> Base32:  the "Base 32 Encoding with Extended Hex Alphabet" as
      specified in [[RFC4648](https://www.rfc-editor.org/rfc/rfc4648)].  Note that trailing padding characters
      ("=") are not used in the NSEC3 specification.

Is support for padding needed?


> base32hex_fast

IMO, it is not worth pulling that much data into the cache.
However, the data in the table could be bswapped to eliminate the bswap in the code.
Bad_char entries could be a single set bit in the hi_byte, then only one branch for bad chars would be required..
though we'd still need to zero the byte after the first bad char... because some bytes are made from 3 input chars.

**Comment by lemire** [comment]
@aqrit

> IMO, it is not worth pulling that much data into the cache.

I agree. This is research.

**Comment by lemire** [comment]
I started implementing the padding check, and almost got it done, but after reading @aqrit 's comment, I am pulling out.

Because the functions return the number of bytes read, it is always easy to check the padding if you want to. All you need is a single loop when the number of bytes read is not a multiple of eight.

**Comment by lemire** [comment]
@aqrit I have implemented your optimizations but it hardly makes a difference performance-wise. :-)

However the code is prettier.

**Comment by lemire** [comment]
Ok. Here is what I get...

```
base32hex_avx                  :   8.02 GB/s  250.6 Ma/s   3.99 ns/d   3.24 GHz  12.91 c/d  61.21 i/d    0.4 c/b   1.91 i/b   4.74 i/c 
base32hex_simd                 :   6.95 GB/s  217.2 Ma/s   4.60 ns/d   3.23 GHz  14.86 c/d  70.21 i/d    0.5 c/b   2.19 i/b   4.72 i/c 
base32hex_fast                 :   2.54 GB/s   79.4 Ma/s  12.60 ns/d   3.21 GHz  40.39 c/d  119.21 i/d    1.3 c/b   3.73 i/b   2.95 i/c 
base32hex_simple               :   2.34 GB/s   73.0 Ma/s  13.70 ns/d   3.20 GHz  43.90 c/d  231.21 i/d    1.4 c/b   7.23 i/b   5.27 i/c 
base32hex_swar                 :   1.99 GB/s   62.2 Ma/s  16.08 ns/d   3.20 GHz  51.51 c/d  230.21 i/d    1.6 c/b   7.19 i/b   4.47 i/c 
b32_pton                       :   0.21 GB/s    6.5 Ma/s  153.07 ns/d   3.19 GHz  488.84 c/d  1429.90 i/d   15.3 c/b  44.68 i/b   2.93 i/c 
```

I am moving the URL Code-used-on-Daniel-Lemire-s-blog/2023/07/20 from Code-used-on-Daniel-Lemire-s-blog/2023/07/20 and pushing a blog post.

**Comment by lemire** [comment]
Blog post:

[Fast decoding of base32 strings](https://lemire.me/blog/2023/07/20/fast-decoding-of-base32-strings/)

**Comment by k0ekk0ek** [comment]
That's some great numbers @lemire! Thank you both!

**Comment by lemire** [comment]
The current code would work even if there is padding. It would simply be lenient about it (e.g., it would accept any character as padding, not just '=').

However, I should note that adding such a check (that the padding is done with '=') would be cheap... I considered adding it as an option (`check_padding=true/false`), but why make the function more complicated than it needs to be?

**Comment by k0ekk0ek** [comment]
The code in NSD doesn't account for anything but valid characters and that code has been in use for a long time. I think it's better not to allow for padding and strictly follow the RFC. If there's a valid use case we can always add it afterwards(?)

**Comment by lemire** [comment]
@k0ekk0ek I think that's what the code we have written does. What I mean by lenient is that as soon as invalid characters are found, you consider that you have terminated the base32 sequence.

Of course, you could have something like....

`F1S6QOJADHQMKS3GCLIN4RB9F1Q6UT37+8***fds`


What is would do is that it would stop at the `+`.

**Comment by k0ekk0ek** [comment]
Sounds good to me :+1:

**Comment by k0ekk0ek** [comment]
@lemire, are you working on a PR? No pressure, just want to know if you want to do the honors or if you want me to integrate the changes :slightly_smiling_face:

**Comment by lemire** [comment]
I can prepare a PR, yes.

**Comment by lemire** [comment]
PR available.
